version: "3.7"

    postgres:
      container_name: 'fib-dev-postgres'
      image: 'postgres:11.2'
      restart: always
      ports:
        - '5432:5432'
      environment:
        - 'POSTGRES_USER=user'
        - 'POSTGRES_DB=fib'
        - 'POSTGRES_PASSWORD=password'

    redis:
      container_name: 'main-dev-redis'
      image: 'redis:5.0.3'
      ports:
        - '6379:6379'
